#cloud-config
#
# Потому что мы будем тестировать вход с паролем.
ssh_pwauth: true

users:
  - name: ansible
    gecos: Ansible User
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    shell: /bin/bash
    ssh_authorized_keys:
      # Мой публичный ключ.
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzGFkQSRFoZus7piWi5CU32sao/2ST/DqOmLbAWmRKg58icjH+ae01tdQX5uqUSs+i4qsTiQQmDI/K7m4sPrrX1pZqoxKsUUADq49l6uSdbtr89s1YkuVjFObud3TWLhINCSkcd0j0EBPNodRUI3DtovFSWT6/0Xr+ZL2okdHDifozfS+TorT80mdQaSF65GzdZnmbVSFQcyUsPUCG2W1cv48TvG86gFoz3+7EdxIH6wa2Qa3rQgxjsr/y8jv58lXIai3BMnjfniKDvrX3l/QxNxysaFXdu44HmP3v5g0UDczS3LsfoJMkC4keoJylfVrJYdU1jKwi409ZvZTygqLg5U9ANRC+6a5K0EZAP0nkxZcmz5PSrP7xJ5wo58duLLU12IR/HFX3c6DvaK+LZjJMC231TE858UEANZHqVBH0i4Vj8VHoKYyAaGiHJR73kfnVu6UhTOoP1DtnU2KiJoToUbRlbKCoyngFZNtEkjwCz2aK4bn5lJmmp4qoFjq1Yu8= ivg@DESKTOP-U11D1U8"
  - name: test
    gecos: Test user
    shell: /bin/bash
    lock_passwd: false
